language: julia

install:
  - for deb in deb deb-src; do echo "$deb http://build.openmodelica.org/apt `lsb_release -cs` release"; done | sudo tee /etc/apt/sources.list.d/openmodelica.list
  - wget -q http://build.openmodelica.org/apt/openmodelica.asc -O- | sudo apt-key add -
  - sudo apt update
  - sudo apt install openmodelica
  # we need the most recent version from the repo for sendExpression("quit()", parsed=false)
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="git@github.com:OpenModelica/OMJulia.jl.git"))' <<< /home/travis/.ssh/id_rsa

script:
  - julia scripts/unittests.jl
