name: Create plots

on:
  workflow_run:
    workflows: [ "Run tests" ]
    branches: [ main ]
    types: [ completed ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Run plotting script
      run: python scripts/plot_mc_compare.py
