name: Run tests

on:
  push:
    branches: [ main ]
    tags: 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.5
    - name: Install OpenModelica
      run: |
        for deb in deb deb-src; do echo "$deb http://build.openmodelica.org/apt `lsb_release -cs` release"; done | sudo tee /etc/apt/sources.list.d/openmodelica.list
        wget -q http://build.openmodelica.org/apt/openmodelica.asc -O- | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install openmodelica
    - name: Install Julia requirements
      run: |
        export PYTHON=""
        julia --project=. -e 'using Pkg; Pkg.instantiate()'
    - name: Run unit tests
      run: julia --project=. scripts/unittests.jl
