name: Run tests

on:
  push:
    branches: [ main ]
    tags: 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # also checkout reference data
    # NOTE: This is not included as a git submodule, because then the parent
    # project SHM would contain shm-ref twice.
    - uses: actions/checkout@v2
      with:
        ref: af136d6ebcc92910c9d7a1ea747edfb2503442f8
        repository: CSchoel/shm-ref
        path: shm-ref
    - name: Link to shm-ref from parent directory
      run: ln -s shm-conduction/shm-ref ../shm-ref
    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.5
    - name: Install OpenModelica
      uses: THM-MoTE/setup-openmodelica@v1
      with:
        version: 1.16.2
    - name: Install Julia requirements
      run: |
        export PYTHON=""
        julia --project=. -e 'using Pkg; Pkg.instantiate()'
    - name: Run unit tests
      run: julia --project=. scripts/unittests.jl
    # only required for plots
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Run plotting script
      run: python scripts/plot_mc_compare.py
