name: Run tests

on:
  push:
    branches: [ main ]
    tags: 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.5
    - name: Install OpenModelica
      uses: THM-MoTE/setup-openmodelica@v0.1.2
      with:
        version: 1.16.2
    #   run: |
    #     for deb in deb deb-src; do echo "$deb http://build.openmodelica.org/apt `lsb_release -cs` release"; done | sudo tee /etc/apt/sources.list.d/openmodelica.list
    #     wget -q http://build.openmodelica.org/apt/openmodelica.asc -O- | sudo apt-key add -
    #     sudo apt-get update
    #     sudo apt-get install openmodelica
    - name: Install Julia requirements
      run: |
        export PYTHON=""
        julia --project=. -e 'using Pkg; Pkg.instantiate()'
    - name: Run unit tests
      run: julia --project=. scripts/unittests.jl
    # only required for plots
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Run plotting script
      run: python scripts/plot_mc_compare.py
